spring:
  application:
    name: TaskManager

  datasource:
    username: postgres
    password: 56cbtm1b
    url: jdbc:postgresql://localhost:5432/tasks_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8090